version: '2.0'
services:
  nginx:
    container_name: app-nginx-testDocker
    image: nginx:latest
    volumes:
      - ./source:/usr/share/nginx/html
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    links:
      - php
  php:
    container_name: app-php-testDocker
    image: php:fpm
    volumes:
      - ./source:/usr/share/nginx/html